<?php

namespace Tests\Unit;

use App\Models\Country;
use App\Models\Provider;
use App\Models\User;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CountryTest extends TestCase
{

    use RefreshDatabase;

    /**
     * @var Country
     */
    private Country $country;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->country = Country::factory()
            ->has(User::factory()->count(3))
            ->has(Provider::factory()->count(3))
            ->create();
    }

    public function test_users_relation()
    {
        $this->assertInstanceOf(HasMany::class, $this->country->users());
        $this->assertInstanceOf(Collection::class, $this->country->users);
        $this->assertCount(3, $this->country->users);
        $this->assertInstanceOf(User::class, $this->country->users->first());
    }

    public function test_providers_relation()
    {
        $this->assertInstanceOf(HasMany::class, $this->country->providers());
        $this->assertInstanceOf(Collection::class, $this->country->providers);
        $this->assertCount(3, $this->country->providers);
        $this->assertInstanceOf(Provider::class, $this->country->providers->first());
    }

}
