<?php

namespace Tests\Unit;

use App\Models\Country;
use App\Models\Product;
use App\Models\ProductPrice;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProductPriceTest extends TestCase
{

    use RefreshDatabase;

    /**
     * @var Country
     */
    private Country $country;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->price = ProductPrice::factory()->create();
    }

    public function test_product_relation()
    {
        $this->assertInstanceOf(BelongsTo::class, $this->price->product());
        $this->assertInstanceOf(Product::class, $this->price->product);
    }

    public function test_datetime_is_casted_to_real_datetime(){
        $this->assertInstanceOf(Carbon::class,$this->price->datetime);
    }

}
