<?php

namespace Tests\Unit;

use App\Models\Product;
use App\Models\ProductCategory;
use App\Models\ProductPrice;
use App\Models\Provider;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProductTest extends TestCase
{

    use RefreshDatabase;

    /**
     * @var Product
     */
    private Product $product;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->product = Product::factory()->has(ProductPrice::factory()->count(3),'prices')->create();
    }

    public function test_category_relation()
    {
        $this->assertInstanceOf(BelongsTo::class, $this->product->category());
        $this->assertInstanceOf(ProductCategory::class, $this->product->category);
    }

    public function test_provider_relation()
    {
        $this->assertInstanceOf(BelongsTo::class, $this->product->provider());
        $this->assertInstanceOf(Provider::class, $this->product->provider);
    }

    public function test_prices_relation()
    {
        $this->assertInstanceOf(HasMany::class, $this->product->prices());
        $this->assertInstanceOf(Collection::class, $this->product->prices);
        $this->assertCount(4, $this->product->prices); //the product observer will create one more price on created event
        $this->assertInstanceOf(ProductPrice::class, $this->product->prices->first());
    }

    public function test_created_observer_creates_a_price_when_a_product_is_created()
    {
        $product = Product::factory()->create();

        $this->assertCount(1,$product->prices);
        $this->assertEquals( (float) $product->current_price, (float)$product->prices->first()->price);
    }

}

