<?php

namespace Tests\Unit;

use App\Models\Country;
use App\Models\Product;
use App\Models\Provider;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ProviderTest extends TestCase
{

    use RefreshDatabase;

    /**
     * @var Provider
     */
    private Provider $provider;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->provider = Provider::factory()
            ->for(Country::factory())
            ->has(Product::factory()->count(3))
            ->create();
    }

    public function test_products_relation()
    {
        $this->assertInstanceOf(HasMany::class, $this->provider->products());
        $this->assertInstanceOf(Collection::class, $this->provider->products);
        $this->assertCount(3, $this->provider->products);
        $this->assertInstanceOf(Product::class, $this->provider->products->first());
    }

    public function test_country_relation(){
        $this->assertInstanceOf(BelongsTo::class,$this->provider->country());
        $this->assertInstanceOf(Country::class,$this->provider->country);
    }
}

